// ROOT dependencies
#include "TApplication.h"
#include "TCanvas.h"
#include "TFile.h"
#include "TH2Poly.h"
#include "TLine.h"
#include "TRandom3.h"

// Dictionaries generated by ROOT
#include "../../build/X17_dict.cxx"

// X17 dependencies
#include "Field.h"
#include "PadLayout.h"
#include "X17Utilities.h"

int main(int argc, char *argv[])
{
    TApplication app("app", &argc, argv);

    // Loading the ionization electron drift map.
    TFile* map_input = new TFile("../../../data/ion_map/sample_2.0/map.root");
    X17::Field<X17::MapPoint>* map = (X17::Field<X17::MapPoint>*)map_input->Get("map");
    
    TRandom3* rand = new TRandom3(0);

    TH2Poly* poly = new TH2Poly();

    // Pad layout to bins
    for (int i = 1; i <= X17::constants::channels; i++)
    {
        double x1,y1,x2,y2;
        X17::DefaultLayout::GetDefaultLayout().GetPadCorners(i,x1,y1,x2,y2,true);
        poly->AddBin(y1,x1,y2,x2);
    }

    // Phi angles ----> normalization (brute force)
    int angle_bins = 21;
    double phi_max = atan((X17::constants::win_width/2)/X17::constants::xmin);    // The maximal simulated phi [rad].
    double phi_min = -phi_max;                                                    // The minimal simulated phi [rad].

    double length_step = 1E-5;
    int pad_hits[X17::constants::channels];
    for (int i = 0; i < X17::constants::channels; i++) pad_hits[i] = 0;

    // For all phi angles, calculate a line
    for (int i = 0; i < angle_bins; i++)
    {
        ReportProgress(i,angle_bins);
        using namespace X17::constants;
        double phi = phi_min + (phi_max - phi_min) * i / (angle_bins - 1);

        // The line is this much longer along it then along x
        double length_factor = 1/std::cos(phi);

        // Therefore, we need smaller x steps
        double x_step = length_step / length_factor;

        for (double x = xmin; x < xmax; x += x_step)
        {
            double y = x * std::tan(phi);
            X17::EndPoint end = map->GetField(x,y,0).GetRandomPoint(rand);
            int pad = X17::DefaultLayout::GetDefaultLayout().GetPad(end.x(),end.y());
            if (pad > 0) pad_hits[pad-1]++;            
        }
    }

    for (int i = 0; i < X17::constants::channels; i++)
    {
        poly->SetBinContent(i+1,pad_hits[i]);
    }

    TCanvas* c = new TCanvas("c_discrete_norm","c_discrete_norm",700,500);
    poly->SetTitle(";y [cm];x [cm]");
    ApplyThesisStyle(c);
    poly->Draw();

    for (int i = 0; i < angle_bins; i++)
    {
        using namespace X17::constants;
        double phi = phi_min + (phi_max - phi_min) * i / (angle_bins - 1);
        TLine* line = new TLine(xmin*std::tan(phi),xmin,xmax*std::tan(phi),xmax);
        line->SetLineColor(kRed);
        line->SetLineWidth(2);
        line->Draw("same");
    }

    ApplyThesisStyle(c);
    c->Modified();
    c->Update();

    app.Run(true);

    return 0;
}