// C++ dependencies
#include <vector>

// ROOT dependencies
#include "TFile.h"
#include "TGraph.h"
#include "TGraph2D.h"
#include "TH3F.h"
#include "TMultiGraph.h"
#include "TPolyLine3D.h"
#include "TTree.h"

// Dictionaries generated by ROOT
#include "../build/X17_dict.cxx"

// X17 dependencies
#include "Color.h"
#include "Track.h"
#include "Utilities.h"

double g_cwidth = 700;
double g_cheight = 500;

int main(int argc, char const *argv[])
{
    TFile* input = new TFile("../../../data/micro_tracks/grid_01/tracks_full1000.root");
    TFile* output = new TFile("driftlines.root","RECREATE");
    TTree* tracks = (TTree*)input->Get("tracks_full");

    // 8 MeV, zero theta, zero phi electron track
    X17::TrackMicro* track = 0;
    tracks->SetBranchAddress("track_full",&track);
    tracks->GetEntry(4);

    std::cout << "Loaded track with " << track->points.size() << " points and " << track->driftlines.size() << " driftlines.\n";

    TMultiGraph* mg_xy = new TMultiGraph();
    TGraph* g_primary_xy = new TGraph();
    std::vector<TGraph*> g_driftlines_xy;
    
    TMultiGraph* mg_xz = new TMultiGraph();
    TGraph* g_primary_xz = new TGraph();
    std::vector<TGraph*> g_driftlines_xz;
    
    TMultiGraph* mg_yz = new TMultiGraph();
    TGraph* g_primary_yz = new TGraph();
    std::vector<TGraph*> g_driftlines_yz;

    TGraph2D* g_primary_3d = new TGraph2D();
    std::vector<TPolyLine3D*> l_driftlines_3d;
    
    for (const auto& point : track->points)
    {
        g_primary_xy->AddPoint(point.start.x(),point.start.y());
        g_primary_xz->AddPoint(point.start.x(),point.start.z());
        g_primary_yz->AddPoint(point.start.y(),point.start.z());

        g_primary_3d->AddPoint(point.start.x(),point.start.y(),point.start.z());
    }

    for (TGraph* g : {g_primary_xy,g_primary_xz,g_primary_yz})
    {
        g->SetLineColor(kBlack);
        g->SetLineWidth(3);
        ApplyThesisStyle(g);
    }

    g_primary_3d->SetLineColor(kBlack);
    g_primary_3d->SetLineWidth(3);
    ApplyThesisStyle(g_primary_3d);
    
    for (const auto& driftline : track->driftlines)
    {
        g_driftlines_xy.push_back(new TGraph());
        mg_xy->Add(g_driftlines_xy.back(),"L");
        g_driftlines_xz.push_back(new TGraph());
        mg_xz->Add(g_driftlines_xz.back(),"L");
        g_driftlines_yz.push_back(new TGraph());
        mg_yz->Add(g_driftlines_yz.back(),"L");

        l_driftlines_3d.push_back(new TPolyLine3D(driftline.size()));

        int i = 0;
        for (const auto& point : driftline)
        {
            g_driftlines_xy.back()->AddPoint(point.x(),point.y());
            g_driftlines_xz.back()->AddPoint(point.x(),point.z());
            g_driftlines_yz.back()->AddPoint(point.y(),point.z());

            l_driftlines_3d.back()->SetPoint(i,point.x(),point.y(),point.z());
            i++;
        }

        for (TGraph* g : {g_driftlines_xy.back(),g_driftlines_xz.back(),g_driftlines_yz.back()})
        {
            g->SetLineColor(X17::Color::GOrange());
            g->SetLineWidth(1);
            ApplyThesisStyle(g);
        }

        l_driftlines_3d.back()->SetLineColor(X17::Color::GOrange());
        l_driftlines_3d.back()->SetLineWidth(1);
    }

    TCanvas* c_xy = new TCanvas("c_xy","XY projection",g_cwidth,g_cheight);
    ApplyThesisStyle(c_xy);
    mg_xy->Add(g_primary_xy, "L");
    mg_xy->GetXaxis()->SetTitle("x [cm]");
    mg_xy->GetYaxis()->SetTitle("y [cm]");
    ApplyThesisStyle(mg_xy);
    mg_xy->Draw("A");
    c_xy->Write();
    
    TCanvas* c_xz = new TCanvas("c_xz","XZ projection",g_cwidth,g_cheight);
    ApplyThesisStyle(c_xz);
    mg_xz->Add(g_primary_xz, "L");
    mg_xz->GetXaxis()->SetTitle("x [cm]");
    mg_xz->GetYaxis()->SetTitle("z [cm]");
    ApplyThesisStyle(mg_xz);
    mg_xz->Draw("A");
    c_xz->Write();
    
    TCanvas* c_yz = new TCanvas("c_yz","YZ projection",g_cwidth,g_cheight);
    ApplyThesisStyle(c_yz);
    mg_yz->Add(g_primary_yz, "L");
    mg_yz->GetXaxis()->SetTitle("y [cm]");
    mg_yz->GetYaxis()->SetTitle("z [cm]");
    ApplyThesisStyle(mg_yz);
    mg_yz->Draw("A");
    c_yz->Write();

    TCanvas* c_xyz = new TCanvas("c_xyz","3D driftlines",g_cwidth,g_cheight);
    ApplyThesisStyle(c_xyz);
    TH3F* scale = new TH3F("scale",";x [cm];y [cm];z [cm]",1,1,21,1,-10,10,1,-2,8); //6,16,1,-0.2,0.2,1,-2,8);
    ApplyThesisStyle(scale);
    scale->Draw();
    g_primary_3d->RemoveDuplicates();
    g_primary_3d->Draw("L same");
    for (TPolyLine3D* l : l_driftlines_3d) l->Draw("same");
    c_xyz->Write();
    
    output->Close();
    
    return 0;
}