// C++ dependencies
#include <iostream>
#include <string>

// ROOT dependencies
#include "TFile.h"
#include "TTree.h"

// Dictionaries generated by ROOT
#include "../build/X17_dict.cxx"

// X17 dependencies
#include "RecoTasks.h"
#include "TrackLoop.h"

int main(int argc, char const *argv[])
{
    // Loading the magnetic field data.
    X17::Field<X17::Vector>* magfield = X17::LoadField("../../data/elmag/VecB2.txt",{-20,-30,-30},{20,30,30},0.5);

    // Loading the ionization electron drift map.
    TFile* map_input = new TFile("../../data/ion_map/sample_2.0/map.root");
    X17::Field<X17::MapPoint>* map = (X17::Field<X17::MapPoint>*)map_input->Get("map");

    // Loading file microscopic tracks one by one.
    X17::TrackMicro* track_Evf_100 = 0;
    TTree track_selection("track_selection","Track selection");
    track_selection.Branch("track_small",&track_Evf_100);
    
    std::string single_track_folder = "../../data/micro_tracks/grid_01/";
    TFile* input = new TFile((single_track_folder + "tracks_small910.root").c_str());
    TTree* tracks910 = (TTree*)input->Get("tracks_small");
    tracks910->SetBranchAddress("track_small",&track_Evf_100);
    tracks910->GetEntry(1);
    track_selection.Fill();
    
    // TrackLoop for single microscopic track.
    TrackLoop* loop = new TrackLoop(*map,magfield);
    loop->make_track_plots = true;
    
    RecoPadsTask* t = new RecoPadsTask();
    loop->AddTask(t);
    // loop->AddTask(new CircleAndRKFitTask(t));
    
    // Loading file with Runge-Kutta tracks.
    // TFile* input2 = new TFile("../../data/rk_tracks/rk_tracks.root");
    // TTree* rk_tracks = (TTree*)input2->Get("rk_tracks");
    
    // TrackLoop for Runge-Kutta simulated tracks.
    // TrackLoop* rk_loop = new TrackLoop(map,magfield);
    // rk_loop->AddTask(new CircleFitEnergyTask());
    // rk_loop->AddTask(new PlotSelectionTask());
    
    // Processing.
    TFile out_file("track_plots.root","RECREATE","Tracks from microscopic simulation");
    loop->ProcessMulti(&track_selection);
    out_file.Close();
    // rk_loop->ProcessRK(rk_tracks);
    
    return 0;
}